name: Replexica
description: Automated AI localization for multilingual software.
author: Replexica

# Define your inputs here.
inputs:
  api-key:
    description: 'Replexica Platform API Key'
    required: true
  pull-request:
    description: 'Create a pull request with the changes'
    required: false
    default: 'false'

runs:
  using: 'docker'
  image: 'action/Dockerfile'
  env:
    REPLEXICA_API_KEY: ${{ inputs.api-key }}
    REPLEXICA_PULL_REQUEST: ${{ inputs.pull-request }}

branding:
  icon: './content/logo.png'
  color: 'black'
