name: Release

on:
  push:
    branches:
      - main

permissions:
  issues: write
  pull-requests: write
  contents: write

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Run Replexica Action
        uses: ./
        env:
          GH_TOKEN: ${{ github.token }}
